.PHONY: clean All

All:
	@echo "----------Building project:[ UOCCarServer - Debug ]----------"
	@cd "UOCCarServer" && "$(MAKE)" -f  "UOCCarServer.mk"
clean:
	@echo "----------Cleaning project:[ UOCCarServer - Debug ]----------"
	@cd "UOCCarServer" && "$(MAKE)" -f  "UOCCarServer.mk" clean
